### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by rafalzda** [0xacb/viewgen#2]
Hi,

I have very very long VIEWSTATE and when I try to decode I have error
"bash: /usr/local/bin/viewgen: Argument list too long" 

![Image of error](https://dl.dropboxusercontent.com/s/y0v2cbnd2yx4toq/20191127_095124.png)

how i can use your tool with viewstate with 175k characters?

**Comment by 0xacb** [comment]
Hey @rafalzda 

Thank you for opening this issue, I’ll add an option to read the viewstate from stdin soon!

**Comment by 0xacb** [comment]
I'm now closing this issue, sorry for the delay.
Reading the payload from stdin and files is now supported.
